### ISSUE TITLE
Moving files in lib/

### ISSUE THREAD

**Issue by miaout17** [andrewytliu/defly#1]
I listened your lightning talk in rubyconf.tw. Nice work. 

Would you mind to move your files in `lib/` directory?
In convention, we will put most files in `lib/defly/` . 

For example, 

```
lib/defly.rb
lib/defly/inspectable.rb
lib/defly/tracable.rb
lib/defly/whinable.rb
```

This is to avoid name collision. 
If we have another gem named `tracable`, it's nature to have a file named `tracable.rb`
One of the file will be shadowed.

**Comment by andrewytliu** [comment]
Thanks for the advice!

This is fixed in 7f13576f2.
